int changeprize(int);
void counter();
void counter1();
void counter2();
void reservation(int *,int,int );
int choice1(void);
void cancel(int *array,int index);       
void ticket1(int choice,char name[10],int id2,int price);
void ticket2(int choice,char name[10],int id2,int price);
void ticket3(int choice,char name[10],int id2,int price);
int cmovie(void);
int movie(void);
void details(void);
